name: Run fed_betting_markets.R hourly

on:
  schedule:
    - cron: "0 * * * *"   # top of every hour, UTC
  workflow_dispatch: {}    # allow manual runs
  push:
    paths:
      - ".github/workflows/run-fed.yml"
      - "fed_betting_markets.R"
      - "renv.lock"

permissions:
  contents: write   # let the workflow commit results back

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # Set up R + renv and restore packages (fast, cached)
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Run the script
      - name: Execute R script
        run: Rscript fed_betting_markets.R

      # Commit and push changed outputs (CSV/PDF) if any
      - name: Commit results
        if: ${{ !cancelled() }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git commit -m "Hourly update"; then
            git push
          else
            echo "No changes to commit."
          fi
